#' Open Scanned Versions of Potentially Citing Works for Inspection
#'
#' \code{examine_citing} opens the Internet Archive's scanned versions of each potentially citing work in a dataframe generated by `find_citing`, highlighting the potential citations
#' 
#' @param df A dataframe representing downloaded texts (the "citing works") generated by `find_citing`
#' 
#' @details
#' `examine_citing` facilitates the process of confirming that the potential citing works returned by `find_citing` actually do contain citations to the cited works.  
#' Such hand-checking is necessary because the `find_citing` function casts a broad net for citing works, returning all works that include the cited work's author that were published in or after the cited work's year of publication.
#' When `examine_citing` runs, it opens the Internet Archive's online, scanned version of the citing work in the default browser. 
#' The matches in the citing work for each cited work are shown in a separate window.
#' The user can then determine whether the citation is a false positive and enter this information in a spreadsheet (using Excel, etc.) to be loaded into R upon completion of the checking process.
#' After all of these determinations have been made for one citing work, the user should press the [return] key to proceed to the next potential citing source, as indicated by the prompt. 
#' 
#'
#' @examples
#' 
#' 
#' @seealso \code{\link{find_citing}}
#' 
#' @importFrom dplyr `%>%` filter
#'
#' @export

examine_citing <- function(df) {
    for (i in seq_len(max(df$citing_source))) {
        cs <- df %>% 
            filter(citing_source == i)
        l <- rev(unique(as.list(cs$archive_link)))
        walk(l, ~ browseURL(.x))
        invisible(readline(prompt="Press [return] to continue to next citing source"))
    } 
}