#' find_citing
#'
#' \code{find_citing} does stuff 
#' 
#' @param df A dataframe representing downloaded texts (the "cited works") whose citation histories are sought; see details.
#' @param corpus_df A dataframe representing a corpus of downloaded texts generated by \code{\link[build_corpus()]{build_corpus}}.
#' @param verbose Should the function provide information about its progress?
#' 
#' @details
#' Details
#' The `find_citing` function casts a broad net for citing works, returning all works that include the cited work's author's last name that were published in or after the cited work's year of publication.
#' 
#' @return A dataframe
#'
#' @examples
#' 
#' @importFrom dplyr `%>%` select mutate filter
#' @importFrom stringr str_detect
#'
#' @export

find_citing <- function(df, corpus, verbose = TRUE) {
    cited_info <- df %>%
        transmute(cited_author = ifelse(str_detect(author, ","), 
                                        str_replace(author, "(^[^,]*).*", "\\1"),
                                        author),
                  cited_year = date,
                  short_title = word(title, start = 1, end = 3, sep = "\\W+") %>% 
                      str_replace_all("\\b[Aa]n?\\b|\\b[Oo]f\\b|\\b[Oo]n\\b|\\b[Tt]he\\b", "") %>%
                      str_replace("^([^,]*),.*", "\\1") %>% 
                      str_replace_all("\\s+", " ") %>% 
                      str_trim()) %>% 
        arrange(cited_author, short_title, cited_year) %>% 
        distinct(cited_author, short_title, .keep_all = TRUE)
    if (verbose) cat("Now searching for: \n")
    
    x <- invoke_rows(.d = cited_info,
                     .collate = "rows",
                     .f = function(cited_author, cited_year, short_title) {
                         if (verbose) cat(paste("\t", cited_author, cited_year, "\n"))
                         later_works <- corpus_df %>% 
                             filter(date >= cited_year)
                         citing_works <- later_works %>%  
                             mutate(citing = ifelse(cited_year <= date, 
                                                    detect_in_file(local_file, cited_author),
                                                    FALSE)) %>% 
                             filter(citing) %>%
                             select(-citing) %>% 
                             progress_message(., verbose = verbose) %>% 
                             mutate(archive_link = paste0("http://archive.org/stream/", id,
                                                          "#search/", cited_author),
                                    city = ifelse(str_detect(publisher, ":"), 
                                                  str_extract(publisher, "^.*?(?=:)") %>% 
                                                      str_replace("(^[^,]*).*", "\\1"),
                                                  str_replace(publisher, "(^[^,]*).*", "\\1")) %>% 
                                        str_replace("^A\\s+", "") %>%
                                        str_replace_all("[\\[\\]]", "") %>%
                                        str_replace("-", " ") %>% 
                                        str_trim(),
                                    cited = paste(cited_author, cited_year)) %>% 
                             omit_duplicate_sources() %>% 
                             select(id, author, date, title, everything()) 
                     } )
    return(x)
}

progress_message <- function(x, verbose = FALSE) {
    if (verbose) cat(paste("\t\t", nrow(x),
                           "potential citing works found \n"))
    return(x)
}
